name: 'Save Feed Cache'
description: 'Composite action to save feed cache'

runs:
  using: "composite"
  steps:
    - name: Save feed cache
      uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: |
          .cache
          public/images/feed-thumbnails
          public/images/feed-icons
        key: ${{ runner.os }}-feed-${{ github.run_id }}
